name: tcc_fabiano
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_ml_vision: ^0.9.2
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+3
  translator: ^0.1.0+7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
