name: tcc_fabiano
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_ml_vision: ^0.9.2+2
  image_picker: ^0.6.1+8
  translator: ^0.1.0+7
  diacritic: ^0.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/remedios.json

  uses-material-design: true

